# Generated by Django 2.2.4 on 2019-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190817_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdraw')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
