# Generated by Django 2.2.4 on 2019-08-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190819_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anymous', max_length=20),
            preserve_default=False,
        ),
    ]
